//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvaSuceljaAplikacije.EntityKlase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int id_karta { get; set; }
        public Nullable<System.DateTime> trenutak_aktivacije { get; set; }
        public Nullable<int> valjanost { get; set; }
        public Nullable<System.DateTime> datum_kupnje { get; set; }
        public int id_vrsta_karte { get; set; }
        public int id_mjesto { get; set; }
        public int id_korisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        public virtual Vrsta_karte Vrsta_karte { get; set; }
    }
}
