//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvaSuceljaAplikacije.EntityKlase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Karta> Karta { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Linija> Linija { get; set; }
        public virtual DbSet<Mjesto> Mjesto { get; set; }
        public virtual DbSet<Stanica> Stanica { get; set; }
        public virtual DbSet<Tramvaj> Tramvaj { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
        public virtual DbSet<Vozac> Vozac { get; set; }
        public virtual DbSet<Vozna_ruta> Vozna_ruta { get; set; }
        public virtual DbSet<Vozni_red> Vozni_red { get; set; }
        public virtual DbSet<Vrsta_karte> Vrsta_karte { get; set; }
    }
}
