//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvaSuceljaAplikacije.EntityKlase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozna_ruta
    {
        public int id_stanica { get; set; }
        public int id_linija { get; set; }
        public Nullable<System.TimeSpan> vrijeme_dolaska { get; set; }
        public Nullable<System.TimeSpan> vrijeme_odlaska { get; set; }
    
        public virtual Linija Linija { get; set; }
        public virtual Stanica Stanica { get; set; }
    }
}
